### ISSUE TITLE
ToolTip.getLeftPadding()

### ISSUE THREAD

**Issue by Nynuzoud** [xizzhu/simple-tool-tip#10]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.github.xizzhu.simpletooltip.ToolTip.getLeftPadding()' on a null object reference
at com.github.xizzhu.simpletooltip.ToolTipView.<init>(ToolTipView.java:81)
at com.github.xizzhu.simpletooltip.ToolTipView.<init>(ToolTipView.java:48)
at com.github.xizzhu.simpletooltip.ToolTipView$Builder.build(ToolTipView.java:397)

**Comment by xizzhu** [comment]
Seems you didn't provide tooltip to the builder.
